RAID = [
    "ℍ𝔸ℙℙ𝕐 𝔹𝕀ℝ𝕋ℍ𝔻𝔸𝕐 ",
    "誕生日おめでとう",
    "GELUKKIGE VERJAARSDAG",
    "GËZUAR DITËLINDJEN",
    "መልካም ልደት",
    "عيد مولد سعيد",
    "ԾՆՈՒՆԴԴ ՇՆՈՐՀԱՎՈՐ",
    "AD GÜNÜN MÜBARƏK",
    "ZORIONAK",
    "З ДНЁМ НАРАДЖЭННЯ",
    "শুভ জন্মদিন",
    "SRETAN ROĐENDAN",
    "ЧЕСТИТ РОЖДЕН ДЕН",
    "FELIÇ ANIVERSARI",
    "HAPPY BIRTHDAY",
    "TSIKU LABWINO LOBADWA",
    "生日快乐",
    "生日快樂",
    "FELICE ANNIVERSARIU",
    "SRETAN ROĐENDAN",
    "VŠECHNO NEJLEPŠÍ K NAROZENINÁM",
    "TILLYKKE MED FØDSELSDAGEN",
    "GEFELICITEERD",
    "FELIĈAN NASKIĜTAGON",
    " PALJU ÕNNE SÜNNIPÄEVAKS",
    "MALIGAYANG KAARAWAN",
    "HYVÄÄ SYNTYMÄPÄIVÄÄ",
    "JOYEUX ANNIVERSAIRE",
    "LOKKIGE JIERDEI",
    "FELIZ ANIVERSARIO",
    "ᲒᲘᲚᲝᲪᲐᲕ ᲓᲐᲑᲐᲓᲔᲑᲘᲡ ᲓᲦᲔᲡ",
    "ALLES GUTE ZUM GEBURTSTAG",
    "ΧΑΡΟΥΜΕΝΑ ΓΕΝΕΘΛΙΑ",
    "જન્મદિવસ ની શુભકામના",
    "BÒN FÈT",
    "BARKA DA RANAR HAIHUWA",
    "HAUʻOLI LĀ HĀNAU",
    "יום הולדת שמח",
    "जन्मदिन मुबारक",
    "Zoo siab hnub yug",
    "BOLDOG SZÜLETÉSNAPOT",
    "TIL HAMINGJU MEÐ AFMÆLIÐ",
    "EZI NCHETA ỌMỤMỤ",
    "SELAMAT ULANG TAHUN",
    "LÁ BREITHE SHONA DUIT",
    "BUON COMPLEANNO",
    "SUGENG TANGGAP WARSA",
    "ಜನ್ಮದಿನದ ಶುಭಾಶಯಗಳು",
    "ТУҒАН КҮНІҢ ҚҰТТЫ БОЛСЫН",
    "រីករាយ​ថ្ងៃ​កំណើត",
    "ISABUKURU NZIZA",
    "생일 축하 해요",
    "ROJBÛNA TE PÎROZ BE",
    "ТУУЛГАН КУНУҢУЗ МЕНЕН КУТТУКТАЙМ",
    "ສຸກ​ສັນ​ວັນ​ເກີດ",
    "FELIX NATALIS",
    "DAUDZ LAIMES DZIMŠANAS DIENĀ",
    "SU GIMTADIENIU",
    "ALLES GUDDES FIR DE GEBUERTSDAG",
    "СРЕЌЕН РОДЕНДЕН",
    "TRATRY NY TSINGERINTAONA NAHATERAHANA",
    "SELAMAT HARI LAHIR",
    "ജന്മദിനാശംസകൾ ",
    "T-TIENU GĦAL",
    "HAPPY RURRY",
    "वाढदिवसाच्या हार्दिक शुभेच्छा",
    "ТӨРСӨН ӨДРИЙН МЭНД",
    "ပျော်ရွှင်စရာမွေးနေ့ဖြစ်ပါစေ",
    "जन्मदिनको शुभकामना",
    "GRATULERER MED DAGEN",
    "ଜନ୍ମଦିନର ଅଭିନନ୍ଦନ",
    "کلیزه دی نیکمرغه",
    "تولدت مبارک",
    "WSZYSTKIEGO NAJLEPSZEGO",
    "FELIZ ANIVERSÁRIO",
    "ਜਨਮਦਿਨ ਮੁਬਾਰਕ",
    "LA MULTI ANI",
    "С ДНЕМ РОЖДЕНИЯ",
    "MANUIA LE ASO FANAU",
    "CO-LÀ-BREITH MATH",
    "СРЕЋАН РОЂЕНДАН",
    "LETSATSI LE MONATE LA TSOALO",
    "BHAVHADHE RINOFADZA",
    "سالگراه مبارڪ ",
    "USUKU OLUMNANDI LOKUZALWA",
    "O KU OJO IBI",
    "גליקלעך דיין געבורסטאָג",
    "USUKU LOKUZALWA OLUMNANDI",
    "PENBLWYDD HAPUS",
    "CHÚC MỪNG SINH NHẬT ",
    "TUG'ILGAN KUNING BILAN",
    "تۇغۇلغان كۈنىڭىزگە مۇبارەك بولسۇن",
    "سالگرہ مبارک",
    "З ДНЕМ НАРОДЖЕННЯ",
    "DOGLAN GÜNÜŇ BILEN",
    "DOĞUM GÜNÜN KUTLU OLSUN",
    "สุขสันต์วันเกิด",
    "పుట్టినరోజు శుభాకాంక్షలు",
    "பிறந்தநாள் வாழ்த்துக்கள்",
    "ТУГАН КӨН БЕЛӘН",
    "GRATTIS PÅ FÖDELSEDAGEN",
    "HERI YA KUZALIWA",
    "WILUJEUNG TEPANG TAUN",
    "FELIZ CUMPLEAÑOS",
    "TDHALASHO WACAN",
    "VSE NAJBOLJŠE",
    "ŠŤASTNÉ NARODENINY",
    "සුබ උපන්දිනයක් වේවා",
    "HAPPY BIRTHDAY",
    "MAY GOD BLESS YOU",    
]

DEADLYSPAM = [1517994352, 2086101519, 136817688]

REPLYRAID = [
    "ℍ𝔸ℙℙ𝕐 𝔹𝕀ℝ𝕋ℍ𝔻𝔸𝕐 ",
    "誕生日おめでとう",
    "GELUKKIGE VERJAARSDAG",
    "GËZUAR DITËLINDJEN",
    "መልካም ልደት",
    "عيد مولد سعيد",
    "ԾՆՈՒՆԴԴ ՇՆՈՐՀԱՎՈՐ",
    "AD GÜNÜN MÜBARƏK",
    "ZORIONAK",
    "З ДНЁМ НАРАДЖЭННЯ",
    "শুভ জন্মদিন",
    "SRETAN ROĐENDAN",
    "ЧЕСТИТ РОЖДЕН ДЕН",
    "FELIÇ ANIVERSARI",
    "HAPPY BIRTHDAY",
    "TSIKU LABWINO LOBADWA",
    "生日快乐",
    "生日快樂",
    "FELICE ANNIVERSARIU",
    "SRETAN ROĐENDAN",
    "VŠECHNO NEJLEPŠÍ K NAROZENINÁM",
    "TILLYKKE MED FØDSELSDAGEN",
    "GEFELICITEERD",
    "FELIĈAN NASKIĜTAGON",
    " PALJU ÕNNE SÜNNIPÄEVAKS",
    "MALIGAYANG KAARAWAN",
    "HYVÄÄ SYNTYMÄPÄIVÄÄ",
    "JOYEUX ANNIVERSAIRE",
    "LOKKIGE JIERDEI",
    "FELIZ ANIVERSARIO",
    "ᲒᲘᲚᲝᲪᲐᲕ ᲓᲐᲑᲐᲓᲔᲑᲘᲡ ᲓᲦᲔᲡ",
    "ALLES GUTE ZUM GEBURTSTAG",
    "ΧΑΡΟΥΜΕΝΑ ΓΕΝΕΘΛΙΑ",
    "જન્મદિવસ ની શુભકામના",
    "BÒN FÈT",
    "BARKA DA RANAR HAIHUWA",
    "HAUʻOLI LĀ HĀNAU",
    "יום הולדת שמח",
    "जन्मदिन मुबारक",
    "Zoo siab hnub yug",
    "BOLDOG SZÜLETÉSNAPOT",
    "TIL HAMINGJU MEÐ AFMÆLIÐ",
    "EZI NCHETA ỌMỤMỤ",
    "SELAMAT ULANG TAHUN",
    "LÁ BREITHE SHONA DUIT",
    "BUON COMPLEANNO",
    "SUGENG TANGGAP WARSA",
    "ಜನ್ಮದಿನದ ಶುಭಾಶಯಗಳು",
    "ТУҒАН КҮНІҢ ҚҰТТЫ БОЛСЫН",
    "រីករាយ​ថ្ងៃ​កំណើត",
    "ISABUKURU NZIZA",
    "생일 축하 해요",
    "ROJBÛNA TE PÎROZ BE",
    "ТУУЛГАН КУНУҢУЗ МЕНЕН КУТТУКТАЙМ",
    "ສຸກ​ສັນ​ວັນ​ເກີດ",
    "FELIX NATALIS",
    "DAUDZ LAIMES DZIMŠANAS DIENĀ",
    "SU GIMTADIENIU",
    "ALLES GUDDES FIR DE GEBUERTSDAG",
    "СРЕЌЕН РОДЕНДЕН",
    "TRATRY NY TSINGERINTAONA NAHATERAHANA",
    "SELAMAT HARI LAHIR",
    "ജന്മദിനാശംസകൾ ",
    "T-TIENU GĦAL",
    "HAPPY RURRY",
    "वाढदिवसाच्या हार्दिक शुभेच्छा",
    "ТӨРСӨН ӨДРИЙН МЭНД",
    "ပျော်ရွှင်စရာမွေးနေ့ဖြစ်ပါစေ",
    "जन्मदिनको शुभकामना",
    "GRATULERER MED DAGEN",
    "ଜନ୍ମଦିନର ଅଭିନନ୍ଦନ",
    "کلیزه دی نیکمرغه",
    "تولدت مبارک",
    "WSZYSTKIEGO NAJLEPSZEGO",
    "FELIZ ANIVERSÁRIO",
    "ਜਨਮਦਿਨ ਮੁਬਾਰਕ",
    "LA MULTI ANI",
    "С ДНЕМ РОЖДЕНИЯ",
    "MANUIA LE ASO FANAU",
    "CO-LÀ-BREITH MATH",
    "СРЕЋАН РОЂЕНДАН",
    "LETSATSI LE MONATE LA TSOALO",
    "BHAVHADHE RINOFADZA",
    "سالگراه مبارڪ ",
    "USUKU OLUMNANDI LOKUZALWA",
    "O KU OJO IBI",
    "גליקלעך דיין געבורסטאָג",
    "USUKU LOKUZALWA OLUMNANDI",
    "PENBLWYDD HAPUS",
    "CHÚC MỪNG SINH NHẬT ",
    "TUG'ILGAN KUNING BILAN",
    "تۇغۇلغان كۈنىڭىزگە مۇبارەك بولسۇن",
    "سالگرہ مبارک",
    "З ДНЕМ НАРОДЖЕННЯ",
    "DOGLAN GÜNÜŇ BILEN",
    "DOĞUM GÜNÜN KUTLU OLSUN",
    "สุขสันต์วันเกิด",
    "పుట్టినరోజు శుభాకాంక్షలు",
    "பிறந்தநாள் வாழ்த்துக்கள்",
    "ТУГАН КӨН БЕЛӘН",
    "GRATTIS PÅ FÖDELSEDAGEN",
    "HERI YA KUZALIWA",
    "WILUJEUNG TEPANG TAUN",
    "FELIZ CUMPLEAÑOS",
    "TDHALASHO WACAN",
    "VSE NAJBOLJŠE",
    "ŠŤASTNÉ NARODENINY",
    "සුබ උපන්දිනයක් වේවා",
    "HAPPY BIRTHDAY",
    "MAY GOD BLESS YOU",    
]
